# Generated by Django 5.2.8 on 2025-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningwatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='planningwatch',
            name='seen_urls',
        ),
        migrations.AddField(
            model_name='planningwatch',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningwatch',
            name='borough_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planningwatch',
            name='query',
            field=models.CharField(max_length=255),
        ),
    ]
