# Generated by Django 5.2.8 on 2025-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_planningwatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningwatch',
            name='last_seen_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='planningwatch',
            name='borough_code',
            field=models.CharField(max_length=50),
        ),
    ]
